### ISSUE TITLE
URL Validation

### ISSUE THREAD

**Issue by nadar** [cebe/luya-module-sitemap#9]
While generate the sitemap i get `The location must be a valid URL. You have specified: https://heartbeat.gmbh/künstliche-intelligenz-für-den-heartbeat-content-hub.` from https://github.com/samdark/sitemap/issues/64 maybe we could encode the url here:

https://github.com/cebe/luya-module-sitemap/blob/master/src/controllers/SitemapController.php#L75-L76

I would send a PR. Maybe afterwards a release 1.0 would be nice 👍

**Comment by cebe** [comment]
> I would send a PR. Maybe afterwards a release 1.0 would be nice +1

Hi, sure go ahead. I am planning to get some other bugs finished until end of May so I would release the 1.0 after that.
